### PR TITLE
slashed

### PR DESCRIPTION
**Pull request by Furtif**
https://github.com/Necrobot-Private/NecroBot/pull/1867

### CODE REVIEW

**Comment by Lord-Haji** [comment]
I don't think a question mark was needed only slash works

**Comment by Furtif** [comment]
yes it is needed because gui wpf canot regrupe 2 png gui only use one png rb uses combination off 2 png png pokemon + slashed png

**Comment by Furtif** [comment]
https://github.com/Furtif/NecroBot/blob/100456a772f8b53283997dca950fdb4267f4dbe5/RocketBot2/Helpers/ResourceHelper.cs#L285

**Comment by Furtif** [comment]
GUI uses (returns string 'http:xxxx') RB uses (return Image)

**Comment by Lord-Haji** [comment]
Possible fix is make a slashed version of every Pokemon then add those

**Comment by Furtif** [comment]
pidgey-slashed.png ?

**Comment by Furtif** [comment]
or copy functions from resourcehelper.cs rb Image loadimage  (string string) resturns Image and uses combination images

**Pull request merged**
